package ru.skillbranch.data.network.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import ru.skillbranch.data.network.database.Member;

import ru.skillbranch.data.network.database.MemberDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig memberDaoConfig;

    private final MemberDao memberDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        memberDaoConfig = daoConfigMap.get(MemberDao.class).clone();
        memberDaoConfig.initIdentityScope(type);

        memberDao = new MemberDao(memberDaoConfig, this);

        registerDao(Member.class, memberDao);
    }
    
    public void clear() {
        memberDaoConfig.clearIdentityScope();
    }

    public MemberDao getMemberDao() {
        return memberDao;
    }

}
